version: '1.0'

services:
  tomcat:
    build: 
      context: ./tomcat
      dockerfile: Dockerfile
    container_name: tomcat
    ports:
      - "8080:8080"
    networks:
      - dockernet
    volumes:
      - ./tomcat/webapps:/usr/local/webapps
    restart: always
    depends_on:
      - server-mysql

  
  server-mysql:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    container_name: server-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dockernet
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: server-mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - dockernet
    restart: always
    depends_on:
      - server-mysql
    


networks:
  dockernet:
    external: true